name: FreezeTag
version: 1.0
author: Randy
main: me.randy.freezetag.Main
description: 
commands:
  start:
    aliases: [begin]
    description: "Starts the freezetag game"
  end:
    aliases: [finish]
    description: "Ends the freezetag game"